# ============================================================
# BLOCO DE DADOS (DATABASE TIER)
# Engloba: Secret + PVC + Deployment + Service
# ============================================================

# 1. Cofre das senhas do Banco (Base64)
apiVersion: v1
kind: Secret
metadata:
  name: segredos-da-livraria-bd
  namespace: meu-primeiro-projeto
data:
  # Lembre, o Base64 de root é 'cm9vdA=='
  mysql-root-senha: cm9vdA== 
  mysql-usuario: YWRtaW5fbGl2cm9z          # admin_livros
  mysql-senha: YWRtaW5fc2VuaGFfMTIz        # admin_senha_123
---

# 2. O Contrato do HD na Rua (Persistent Volume Claim)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: disco-pvc-mysql-livraria          # "Quero um HD pra Livraria"
  namespace: meu-primeiro-projeto
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi                        # Apenas 2 Gigabytes de bloco

---

# 3. O Cofre Virtual Trancado de Acesso (Service PABX)
apiVersion: v1
kind: Service
metadata:
  name: svc-mysql-banco                  # O NOME DO CORE-DNS INAMOVÍVEL (O Backend usará ISSO)
  namespace: meu-primeiro-projeto
spec:
  type: ClusterIP                        # REDE CORTADA DO MUNDO EXTERNO. ISOLADA.
  selector:
    camada: database
  ports:
    - port: 3306                         # A porta padrão onde os clientes JDBC batem

---

# 4. O Sistema em si rodando (Deployment)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-mysql-livraria
  namespace: meu-primeiro-projeto
spec:
  replicas: 1                            # Nunca suba 2 Replicas do MYSQL Stateless se não houver GaleraCluster config!
  selector:
    matchLabels:
      camada: database
  template:
    metadata:
      labels:
        camada: database
    spec:
      containers:
        - name: mysql-app
          image: mysql:8.0
          
          # Injeção das senhas pegando la do SECRET blindado (Nível Modulo 04)
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: segredos-da-livraria-bd
                  key: mysql-root-senha
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: segredos-da-livraria-bd
                  key: mysql-usuario
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: segredos-da-livraria-bd
                  key: mysql-senha
                  
          ports:
            - containerPort: 3306
            
          # O Plug no fundo da caixa (Nivel Modulo 05)
          volumeMounts:
            - name: storage-mysql
              mountPath: /var/lib/mysql
              
      # Amarração do Chassi ao cabo do PVC:
      volumes:
        - name: storage-mysql
          persistentVolumeClaim:
            claimName: disco-pvc-mysql-livraria
