# ============================================================
# O QUE ESTE ARQUIVO FAZ:
# Cria uma ServiceAccount (Conta de Serviço). Ela é o
# "Crachá Máquina" projetado para os Pods (Aplicações) poderem  
# provar quem são no K8s, igual você, Humano T.I, prova quem é com User/Senha.
# ============================================================

# 1. ANALOGIA DO DIA A DIA
# Quando você ("João", humano Dev DevOps) entra no seu Laptop, você 
# digita seu username e password. Você ganha do sistema um **Token de Identidade**.
# Esse Token diz "Você é o João Humano" o dia inteiro.
# 
# Porem, quando um Pod nasce no Cluster pra ler algo na rede... O POD (O Robô)
# também precisa pedir ingresso num arquivo. Que login ele usa? Ele usa crachá?
# Sim! E o nome do Crachá Robótico que nós criamos pra ele assinar as ações chama-se **ServiceAccount**.

# 2. O QUE É (definição técnica Senior)
# `ServiceAccount` fornece uma identidade estática para processos (pods) que 
# executam dentro de um Cluster. Quando você faz uma requisição HTTP programática pra API
# (do kube-apiserver) de DENTRO do seu container, aquela chamada é validada via um
# Json Web Token (JWT) secretamente montado pelo Kubelet que assina a autoria apontando pra essa SA.

# ============================================================
# 3. ARQUIVO YAML COMENTADO
# ============================================================
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cracha-do-meu-microservico   # O nome estampado no crachá
  namespace: meu-primeiro-projeto    # IMPORTANTE: ServiceAccounts vivem restritas aos namespaces dela!

# Obs: Apenas criar essa pequena declaração de 5 linhas já faz  
# o ControlPlane gerar em background o Cripto-Token único associado a ela!

# ============================================================
# 4. COMANDOS PASSO A PASSO
# ============================================================
# 1. Imprima o Crachá na fábrica do cluster:
#    kubectl apply -f 01-serviceaccount.yaml
#
# 2. Veja ele guardado no banco de identidades:
#    kubectl get serviceaccounts -n meu-primeiro-projeto
#    (Pode abreviar digitando apenas "kubectl get sa").

# ============================================================
# 5. VERIFICAÇÃO E TROUBLESHOOTING
# ============================================================
# Quando um Júnior levanta um Pod e NÃO CITA em lugar nenhum qual `ServiceAccount` 
# aquele Pod deve usar, o K8s magicamente INJETA à força uma Conta chamada "default"
# dentro do seu Pod escondido. Essa conta base é puramente fantasma e não pode fazer 
# basicamente NADA no K8s por design de segurança.

# ============================================================
# 6. CONCEITO SENIOR (o "porquê" profundo)
# ============================================================
# "Elias, mas pra que eu quero que o meu App identifique quem ele é pelo SA?"
# 1º: Cloud IAM Identity Aware:  Na AWS, se eu associar uma Annotation da "Aws-Role"
#     diretamente a ESSE `ServiceAccount` do K8s.. O meu JAVA que herdá-lo 
#     vai poder fazer PutObject livremente no Banco S3 da nuvem DE FORMA NATIVA  
#     SEM PRECISAR CHUMBAR `AWS_KEY` E `AWS_SECRET` de string no codigo! A nuvem entende o Crachá do k8s.
# 2º: Auditoria de Segurança: Se invadirem o seu Pod Java que estava usando esse SA, e o hacker  
#     der o comando destrutivo `kubectl delete pods` de lá de dentro do terminal shell,  
#     o log do Control Plane mostrará que foi a entidade "cracha-do-meu-microservico" quem 
#     fez o ato e você consegue caçar quem foi a aplicação raiz estourada.

# ============================================================
# 7. PERGUNTA DE ENTREVISTA
# ============================================================
# Pergunta: "Para onde vai o arquivo de senha exato JWT quando atrelamos 
# um ServiceAccount no YAML explícito de spec dum arquivo 'Deploy.yaml'? Como o Curl 
# de dentro do linux enxerga ele?"
# Resposta Esperada: "Ao associarmos o campo estrito `spec.serviceAccountName: nome-tal`
# num manifesto, o Kubelet por baixo dos panos ejetará dinâmicamente um TmpFs Volume  
# fixo no diretório de sistema root Linux: `/var/run/secrets/kubernetes.io/serviceaccount`.  
# O Container tem total acesso de leitura do arquivo estourado chamado `token` lá dentro 
# do qual passará pelo HTTP HEADER Bearer nas API Calls pro master."
