# ============================================================
# O QUE ESTE ARQUIVO FAZ:
# Define a "Role" (O Papel / O Livro de Regras). Esse artefato
# estritamente cataloga QUAIS ações de leitura ou escrita podem
# ou não serem executadas estritas à UM ÚNICO Nnamespace Isolado.
# ============================================================

# 1. ANALOGIA DO DIA A DIA
# A Aula 1 (ServiceAccount) imprimiu o nosso  Crachá Físico do robo sem permissao nenhuma.
# Esta **Role** é a folha de Manual de Regras grudada na porta da Gerência RH. 
# Nessa folha (A Role) diz: "Quem assumir este PAPEL aqui, pode VER a folha salarial 
# e COPIAR o excel, mas  NÃO PODE DELETAR CADEIRA DA SALA".
# E detalhe: Essa Role "RH" foi desenhada e vale APENAS pro 5º Andar (Seu Namespace local).

# 2. O QUE É (definição técnica Senior)
# Uma Role constitui os fundamentos do Role-Based Access Control (RBAC). 
# Ela é apenas uma Coleção de "Permissões aditivas" em JSON/YAML. 
# Não existem "Rules" de NEGAR ("Ex: PROÍBO deletar p/ todo mundo"). No k8s TUDO JÁ É 
# PROIBIDO como premissa zero. Toda "Rule" é um "Permit" explícito e afirmativo. 

# ============================================================
# 3. ARQUIVO YAML COMENTADO
# ============================================================
apiVersion: rbac.authorization.k8s.io/v1  # Note o grupo pesado da API (RBAC)
kind: Role
metadata:
  name: regra-de-poder-ler-pods           # O Título da pagina de Regras
  namespace: meu-primeiro-projeto         # Restrito A ESTA SALA!!! 
rules:
  # O Bloco core! O que este papel habilita você a fazer se você vier a vesti-lo:
  - apiGroups: [""]                       # "" Significa o grupo core base do K8s (Pods, Services...)
    resources: ["pods", "pods/log"]       # EM QUAL tipo de coisas você pode por a mão? (SÓ PODS)
    verbs: ["get", "list", "watch"]       # O QUE você pode fazer em pods? (Só VER, não pode Deletar!)
    
  # Outra regra na mesma lista para outros objetos:
  - apiGroups: ["apps"]                   # Deployments moram no grupo "apps" se lembra do começo do arquivo lá? `apiVersion: apps/1` 
    resources: ["deployments"]
    verbs: ["get"]                        # SÓ ver o status de Deployment de curioso.

# ============================================================
# 4. COMANDOS PASSO A PASSO
# ============================================================
# 1. Adicione o manual de regras no mural do andar / namespace:
#    kubectl apply -f 02-role.yaml
#
# 2. Liste as Roles locais do seu namespaces:
#    kubectl get roles -n meu-primeiro-projeto

# ============================================================
# 5. VERIFICAÇÃO E TROUBLESHOOTING
# ============================================================
# Você não toma Erro de crash ao CRIAR Role. Mas o App amarrado nele 
# chora lagrimas de "HTTP 403 Forbidden" ou "Unauthorized" no Kernel. 
# Uma dica MESTRE: Para debugar um objeto se você realmente ta com 
# o poder vestido na vida real local pra rodar o terminal: 
# `kubectl auth can-i delete pods -n meu-primeiro-projeto`.
# Ele vai te cuspir um orgulhoso "yes" ou decepcionante "no". Perfeito pra testar!

# ============================================================
# 6. CONCEITO SENIOR (o "porquê" profundo)
# ============================================================
# "Elias, se eu quiser criar uma Role Global do K8S do mundo interio pra  
# um Admin L2 não precisar replicar a Role em todos os namespaces 1 por 1?".
# Então você NÃO cria um arquivo `kind: Role`. O 'Role' é burro pra cacete. Ele
# serve apenas e unicamente pro Namespace dele da Metadata, cravado! 
# Para poderes GERAIS de nível MUNDIAL e Global do Kube inteiro, existe o irmão
# C.E.O dele: o `kind: ClusterRole`, que veremos em breve.

# ============================================================
# 7. PERGUNTA DE ENTREVISTA
# ============================================================
# Pergunta: "Se nós criarmos uma 'Role' local e escrevermos a Rule do recurso  
# `resources: ["nodes"]` e der aplicar... um ServiceAccount nesse Namespace com 
# com ela vestida vai conseguir Listar os Nós fisicos do Cluster inteiro de leitura?"
# Resposta Esperada: "Absolutamente. Não! O Kube-Apiserver rejeitará a validade do ato.
# Componentes topologicos da categoria 'Nodes', 'PersistentVolumes Globais' ou 'Namespaces'
# SÃO EXCLUSIVOS DE CLUSTER SCOPE. Uma Role.yaml de Namespace é deficiente pra autorizar
# visão de Níveis Superiores ao teto isolado local dela. Somente um `ClusterRole` consegue."
