# ============================================================
# O QUE ESTE ARQUIVO FAZ:
# Cria a Ligação Mágica (O Binding). A peça do quebra-cabeça
# que veste o Crachá do Robô (Aula 1) e o cola no Papel de Regras
# do Mural (Aula 2), dando a real autorização de acesso ao vivente.
# ============================================================

# 1. ANALOGIA DO DIA A DIA
# Lembra da historinha?
# 1. Eu havia imprimido o Seu Crachá plástico (ServiceAccount) vazio = Aula 1. 
# 2. O RH havia colocado no Mural da parede as Regras (Role) que dizem "Pode listar Pods" = Aula 2.
#
# AGORA NA AULA 3 É O ATO FINAL DE EFETIVAR CONTRATO (Binding!):
# O RoleBinding entra no RH e cola o Símbolo oficial da regra de 'Ler Pods' NO SEU CRACHÁ.
# Sem O RoleBinding vinculando os dois... O SA fica pelado. E A Rule no quadro não aplica em ninguém!
# Você é Ninguém de crachá sem o Binding. Todo acesso do K8s é por Bindings.

# 2. O QUE É (definição técnica Senior)
# O `RoleBinding` concede ativamente as permissões declarativas definidas na  
# Role a um Sujeito alvo referenciado (Subject). 
# Esse alvo pode ser User Físico, Um AD "Group" Humano, ou o Crachá Robótico de 
# um app (O "ServiceAccount").

# ============================================================
# 3. ARQUIVO YAML COMENTADO
# ============================================================
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding                     # BINDING: A Corrente de amarração 
metadata:
  name: linca-o-poder                 # Nome do documento de amarração
  namespace: meu-primeiro-projeto 
  
# PARTE A)  QUEM VAI VESTIR A ROUPA / PODER?
subjects:
- kind: ServiceAccount                # Tipo: "É um Crachá de App" 
  name: cracha-do-meu-microservico    # Nome EXATO do arquivo "01" (O Crachá impresso)
  namespace: meu-primeiro-projeto     # Em qual sala do RH esse sujeito mora

# PARTE B) QUAL ROUPA MAGICA (REGRA) ELE VAI VESTIR NAS COSTAS?
roleRef:
  kind: Role                          # Tipo: "Quero ligar num Mural de Role Local"
  name: regra-de-poder-ler-pods       # Nome EXATO do Mural do arquivo "02"
  apiGroup: rbac.authorization.k8s.io # O Core API da engine validadora do control plane

# ============================================================
# 4. COMANDOS PASSO A PASSO
# ============================================================
# 1. Antes de mais nada, tenha certeza de aplicar as aulas `01 e 02` anteriores caso não haja feito.
#    Feito? Lance a marreta de contrato "Bindando" as duas no mundo K8S:
#    kubectl apply -f 03-rolebinding.yaml
#
# 2. Liste as amarrações do seu Namespace local de projeto:
#    kubectl get rolebindings -n meu-primeiro-projeto

# ============================================================
# 5. VERIFICAÇÃO E TROUBLESHOOTING
# ============================================================
# COMO DESCUBRO AGORA QUANTO PODER EU DE FATO TENHO? 
# Seus dias de Debug de permissão caóticos acabaram, anote no coração e decore:
# Eu Quero tentar me passar por ESTE CRACHA ABAIXO, pra ver MENTLAMENTE NO TERMINAL 
# se ele logicasse ele teria o 'SIM' ou 'NAO' pra de fato listar Pods? 
# Rode ao vivo a magia do 'as' (impersonate):
#
# `kubectl get pods --as=system:serviceaccount:meu-primeiro-projeto:cracha-do-meu-microservico`
#
# Ele vai printar a lista linda de PODS com Sucesso! 
# E agora se eu meter o LOUCO tentando me passar por ele pra DELETAR?
# `kubectl auth can-i delete pods --as=system:serviceaccount:meu-primeiro-projeto:cracha-do-meu-microservico`
# A RESPOSTA MAGISTRAL LOGO ABAIXO DA SAIDA  DO CLI: "no".
# (Perfeição absoluta de RBAC Segura do livro de regras!)

# ============================================================
# 6. CONCEITO SENIOR (o "porquê" profundo)
# ============================================================
# O RoleBinding do K8s é imutável no tocante à *Qual Roupa (`roleRef`)* ele veste num Sujeito..
# Se um Junior entrar no YAML ai em cima `03-rolebinding.yaml`, alterar a linha 24 pra outro nome
# (`name: REGRA_PODEROSA_NOVA_DE_ADMIN`) e aplicar um "kubectl apply -f" por cima disso...  
# O kubernetes emite um ERRO FATAL "Invalid... Invalid value: roleRef is immutable". 
# Regra Senior de Segurança: Um atestado de união RBAC, depois de lacrado o carimbo,
# não pode simplesmente trocar de Livro de Regras por Hot-Reload. Evita sequestros de YAML
# obscuros e "Privilege Escalations". Tem quer dar delete e recreate manual com auditoria de log.

# ============================================================
# 7. PERGUNTA DE ENTREVISTA
# ============================================================
# Pergunta: "Se nós temos uma Role local em "Dev" apontada em um Rolebinding aliás na sala de "Dev".
# Pra economizar arquivo Yamls soltos, nós podemos botar O SUBJECT (Quem vai vestir) sendo  
# um ServiceAccount do NAMESPACE da *`PRODUCAO`*? Daria Binding cruzado?" 
# Resposta Esperada: "Sim, sem dúvidas. Esse é incrivelmente o truque mestre de CI/CD.
# Nós podemos ter o Jenkins rodando na Producao (Possui seu crachá Jenkins-SA) e na aba 'Subjects' 
# do arquivo Rolebinding da sala de Desenvolvmento DEV, apontar dizendo: "Hey, quando
# a conta de 'Prdoucao/Jenkins-SA' se logar.. ela vira LIDER nesta sala". E o Jenkins 
# da Produção magicamente ganha autoridade pra agir no vizinho dele!"
